### ISSUE TITLE
Now the truth, I missed

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#65] opened 2015-06-12 18:00 UTC
Ysurac now, I think I missed and the truth is not like following, if my settings are not right, not if the dbs, I have the right, or do not know how to put it in install_ivao.

I need some help because you faster than the wind.

Might go over a bit to see if you think I have it all right ?. I would greatly appreciate it for real.

**Comment by Ysurac** [comment] 2015-06-12 18:46
What is the problem ?

**Comment by tonkepen100** [comment] 2015-06-13 09:35
See by parties that now if I'm rolling a little:

A.- Tables...

![tablas](https://cloud.githubusercontent.com/assets/4571086/8143796/97f57ece-11be-11e5-9b11-d45b918f89f5.PNG)

These are the tables that I have now, you think you are all that you are?.

B.- Config..

This is my configuration file, and it kept changing as they ivan varying repositories, you think ?, okay for me if Piro ...

<?php
//INSTALLED OR NOT ?
$globalInstalled = TRUE;

//GLOBAL SITE NAME
$globalName = 'AirPiro Radar';

// GLOBAL URL
$globalURL = '';

// Logo URL
$logoURL = '/images/logo2.png';

// Activate debug
$globalDebug = FALSE;

// LANGUAGE
$globalLanguage = 'EN'; // Used only for wikipedia links for now

// MAP PROVIDER
$globalMapProvider = 'MapQuest-OSM'; // Can be Mapbox, OpenStreetMap, MapQuest-OSM or MapQuest-Aerial
$globalMapboxId = 'tonkpe.mdaj2h'; // Mapbox id
$globalMapboxToken = 'pk.eyJ1IjoidG9ua2VwZSIsImEiOiJuZkI2SWRZIn0.dOHW4NeEsjF7UpAgZBg'; // Mapbox token

//COVERAGE AREA (its based on a box model. i.e. top-left | top-right | bottom-right | bottom-left)
$globalLatitudeMax = ''; //the maximum latitude (north)
$globalLatitudeMin = ''; //the minimum latitude (south)
$globalLongitudeMax = ''; //the maximum longitude (west)
$globalLongitudeMin = ''; //the minimum longitude (east)

$globalCenterLatitude = '20.38'; //the latitude center of your coverage area
$globalCenterLongitude = '5.29';//the longitude center of your coverage area

$globalLiveZoom = '3'; //default zoom on Live Map

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$globalDistanceIgnore = array();
// ^^ example for 100km : array('latitude' => '46.38','longitide' => '5.29','distance' => '100');

// DATABASE CONNECTION LOGIN
$globalDBdriver = 'mysql'; // PDO driver used. Tested with mysql, maybe pgsql or others work...
$globalDBhost = 'localhost'; //database connection url
$globalDBuser = 'OLEEEEEEEEEEE'; //database username
$globalDBpass = 'OLEEEEEEEEEE'; //database password
$globalDBname = 'OLEEEEEEEEEEE'; //database name
$globalTransaction = TRUE; //Activate database transaction support


//FLIGHTAWARE API INFO
$globalFlightAware = FALSE; //set to TRUE to use FlightAware as data import
$globalFlightAwareUsername = ''; //FlightAware Username
$globalFlightAwarePassword = ''; //FlightAware Password/API key

// TIMEZONE
$globalTimezone = 'Europe/Madrid';

// DAEMON
$globalDaemon = FALSE; // Run cron-sbs.php as daemon (don't work well if source is a real SBS1 device)
$globalCronEnd = '120'; //the script run for xx seconds if $globalDaemon is disable in SBS mode

// FORK
$globalFork = TRUE; // Allow cron-sbs.php to fork to fetch schedule, no more schedules fetch if set to FALSE

// DISPLAY FLIGHT INTERVAL ON MAP (in seconds)
$globalLiveInterval = '120';

// LIVE MAP REFRESH (in seconds)
$globalMapRefresh = '120';

//ADS-B, SBS1 FORMAT
$globalSBS1 = TRUE; //set to FALSE to not use SBS1 as data import
$globalSBS1Hosts = array('http:','http:','http:','http://piro.biz/lib/skins/skyline/js/recentpireps.php','');
// ^^ in the form array('87.222.37.143:30003','87.222.37.143:30004','http://xxxxx/whazzup.txt');(can be deltadb.txt or aircraftlist.json url to Radarcape, or /action.php/acars/data of phpvms, or wazzup file format);
$globalSBS1TimeOut = '15';
$globalSBS1update = '600'; //Put data in DB after xx seconds/flight

//ACARS Listen in UDP
$globalACARS = FALSE;
$globalACARSHost = '0.0.0.0'; // Local IP to listen
$globalACARSPort = '9999';

//NOTAM
$globalNOTAM = TRUE;
$globalNOTAMSource = ''; //URL of your feed from notaminfo.com

// To display Squawk usage we need Squawk country for now
$globalSquawkCountry = 'US';

//BIT.LY API INFO (used in the search page for a shorter URL)
$globalBitlyAccessToken = 'R_b73b08ae7c8a4b87b1ba50d2f7d7f'; //the access token from the bit.ly API

//BRITISH AIRWAYS API INFO
$globalBritishAirwaysKey = 'u88an5tqkqne4m4z7nhmwc';

//ignore the flights during imports that have the following airports (departure/arrival) associated with them
$globalAirportIgnore = array();

//Archive all data
$globalArchive = TRUE;

//Sources for Aircraft image (should be set to array() if no real aircrafts)
$globalAircraftImageSources = array('wikimedia','deviantart','flickr','bing','jetphotos','planepictures','planespotters');

//Sources for airline schedule (should be set to array() if no real aircrafts or/and set $globalFork = FALSE )
$globalSchedulesSources = array('flightmapper','costtotravel','flightradar24','flightaware');

//Sources for translation, to find name of flight from callsign (set to array() to disable)
$globalTranslationSources = array();
$globalSchedulesFetch = FALSE;
$globalIVAO = TRUE;
$globalTranslationFetch = FALSE;
$globalNOTAMSource = '';
$globalNOTAM = TRUE;
$globalAircraftSize = '25';
?>

C.- Update Tables....

Now I see that there are two files populate one of ivao and another always to do?


![captura](https://cloud.githubusercontent.com/assets/4571086/8143815/96deaeba-11bf-11e5-835f-c4173e01c29f.PNG)

D.- Notams

Referring to Notams, and in my case that direction would have to make, because I do not understand the issue too well.

As always Yurac thanks for your patience, Mr.'re a expeccional person

**Comment by Ysurac** [comment] 2015-06-13 18:04
change **$globalSBS1Hosts** to : *$globalSBS1Hosts = array('http:','http://piro.biz/lib/skins/skyline/js/recentpireps.php');*
If you want NOTAM, you have to register to **notaminfo.com** and use the url of the RSS feed as **$globalNOTAMSource**
For IVAO, as **populate_icao.php** say, you have to download the file ivae_feb2013.zip from https://www.ivao.aero/softdev/mirrors.asp?software=IvAeDataUp and put it in install/tmp directory (fixed in latest commit). (No choice, they don't allow direct download...)

**Comment by tonkepen100** [comment] 2015-06-13 18:50
Ivao file that goes Temp, I put rar as you download or upload it to the two folders you bring?

Thanks Ysurac.

**Comment by Ysurac** [comment] 2015-06-13 18:57
it's a zip file, **ivae_feb2013.zip**, you have to put this zip file in **install/tmp/**. Then put **$globalInstalled** in *require/settings.php* to **FALSE** and run **install/populate_ivao.php**.

**Comment by tonkepen100** [comment] 2015-06-13 19:08
ok go thanks

**Comment by tonkepen100** [comment] 2015-06-13 19:43
Yurac already followed your steps and told me what to charge ivao well.

**Comment by Ysurac** [comment] 2015-06-13 19:51
All seems to be ok. it's working.

**Comment by tonkepen100** [comment] 2015-06-13 19:57
I already registered Ysurac in notam, you think that's good because? ...


$globalNOTAMSource = 'http://notaminfo.com/spainmap';
$globalNOTAM = TRUE;
$globalAircraftSize = '25';

![captura](https://cloud.githubusercontent.com/assets/4571086/8145787/1a97ffd4-1217-11e5-971c-8533637db881.PNG)

**Comment by Ysurac** [comment] 2015-06-13 19:59
for notam you need the RSS feed. It's in the form **http://notaminfo.com/feed?u=YOURUSERNAME**

**Comment by Ysurac** [comment] 2015-06-13 20:01
I was telling it's OK for IVAO, all IVAO airlines & logos are here for your install.

**Comment by tonkepen100** [comment] 2015-06-13 20:22
Ohhhhhhhhhhhhhhh yessssssssssssssss

**Comment by tonkepen100** [comment] 2015-06-14 09:45
Ysurac sensational and everything works, least of notams, that I can not put it right, I'll go and see mirndo it can be.

We are now presenting a little mistake, it turns out that the meter IVAO, the clear companis double, grabs the IVAO and real and doubles ... look ..

![captura](https://cloud.githubusercontent.com/assets/4571086/8148085/cccf6c50-128a-11e5-9a87-a60f6f712b31.PNG)

**Comment by Ysurac** [comment] 2015-06-14 15:58
It's not a bug. An airline company can use multiple ICAO (it's often the case when an airline buy another airlines). They can then have the same logo but can be for a region of the world. It's the case with Easyjet in real airlines.

**Comment by tonkepen100** [comment] 2015-06-15 05:21
No look I think what happens is, the logos of actual companies are in PNG, while climbing Ivao rar are in GIF, so duplicate, one in PNG and one in gif.

**Comment by tonkepen100** [comment] 2015-06-15 05:39
look at is that out of grabs in png format, but when you click the grabs in Guif
![captura](https://cloud.githubusercontent.com/assets/4571086/8153689/aaed7918-1331-11e5-88f2-0b67ff153078.PNG)
![captura1](https://cloud.githubusercontent.com/assets/4571086/8153692/ad573ce8-1331-11e5-9347-79a635f18bdb.PNG)

**Comment by Ysurac** [comment] 2015-06-15 06:32
The use of PNG in IVAO instead of GIF is fixed in commit df3c9dc but this will make no change for "duplicate" airlines logo.

**Comment by tonkepen100** [comment] 2015-06-15 06:37
Ysurac understood thanks.

**Closed** 2015-06-15 09:09 UTC
